(() => {
  const endpoint = "https://ybugwhgdjqwvjvfpcvhe.supabase.co/functions/v1/chat-assistant";
  const messages = [];
  const root = document.createElement("section");
  root.innerHTML = `<style>
    #ai-chat{position:fixed;right:20px;bottom:20px;z-index:9999;font:15px/1.45 Arial,sans-serif;color:#16302a}#ai-chat button{font:inherit}#ai-chat-toggle{width:56px;height:56px;border:0;border-radius:50%;background:#0a7b63;color:#fff;font-size:24px;box-shadow:0 8px 24px #0003;cursor:pointer;float:right}#ai-chat-panel{display:none;clear:both;width:min(360px,calc(100vw - 32px));height:500px;margin-bottom:12px;background:#fff;border:1px solid #cbd8d4;border-radius:8px;box-shadow:0 16px 40px #0003;overflow:hidden;flex-direction:column}#ai-chat.open #ai-chat-panel{display:flex}.ai-head{padding:14px 16px;background:#0a7b63;color:#fff;font-weight:700}.ai-note{padding:8px 16px;background:#eef7f4;font-size:12px}.ai-log{flex:1;overflow:auto;padding:14px;background:#fbfdfc}.ai-msg{max-width:84%;margin:0 0 10px;padding:9px 11px;border-radius:8px;white-space:pre-wrap}.ai-user{margin-left:auto;background:#d8f0e8}.ai-bot{background:#fff;border:1px solid #dbe6e2}.ai-form{display:flex;gap:8px;padding:12px;border-top:1px solid #dbe6e2}.ai-form textarea{flex:1;resize:none;border:1px solid #9db3ac;border-radius:6px;padding:9px;font:inherit}.ai-form button{border:0;border-radius:6px;background:#0a7b63;color:#fff;padding:0 12px;cursor:pointer}@media(max-width:480px){#ai-chat{right:12px;bottom:12px}#ai-chat-panel{height:min(520px,calc(100vh - 100px))}}</style><div id="ai-chat"><div id="ai-chat-panel" role="dialog" aria-label="Trợ lý tư vấn"><div class="ai-head">Trợ lý chăm sóc sức khỏe</div><div class="ai-note">Thông tin chỉ mang tính tham khảo, không thay thế chẩn đoán y khoa.</div><div class="ai-log" aria-live="polite"></div><form class="ai-form"><textarea rows="2" maxlength="1200" placeholder="Nhập câu hỏi của bạn" aria-label="Câu hỏi"></textarea><button type="submit">Gửi</button></form></div><button id="ai-chat-toggle" aria-expanded="false" aria-label="Mở trợ lý tư vấn">?</button></div>`;
  document.body.append(root);
  const chat = root.querySelector("#ai-chat"), toggle = root.querySelector("#ai-chat-toggle"), log = root.querySelector(".ai-log"), form = root.querySelector("form"), input = root.querySelector("textarea"), send = root.querySelector("form button");
  const add = (text, role) => { const item = document.createElement("div"); item.className = `ai-msg ai-${role}`; item.textContent = text; log.append(item); log.scrollTop = log.scrollHeight; };
  add("Chào bạn. Mình có thể hỗ trợ thông tin tham khảo về chăm sóc sức khỏe chủ động.", "bot");
  toggle.onclick = () => { const open = chat.classList.toggle("open"); toggle.setAttribute("aria-expanded", String(open)); if (open) input.focus(); };
  form.onsubmit = async (event) => { event.preventDefault(); const text = input.value.trim(); if (!text) return; messages.push({ role: "user", content: text }); add(text, "user"); input.value = ""; send.disabled = true; add("Đang trả lời...", "bot"); const pending = log.lastElementChild; try { const response = await fetch(endpoint, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ messages: messages.slice(-12) }) }); const data = await response.json(); pending.remove(); if (!response.ok) throw new Error(data.error); messages.push({ role: "assistant", content: data.reply }); add(data.reply || "Mình chưa thể trả lời lúc này.", "bot"); } catch { pending.textContent = "Kết nối đang bận. Vui lòng thử lại sau hoặc để lại thông tin trong biểu mẫu."; } finally { send.disabled = false; input.focus(); } };
})();
